### ISSUE TITLE
Val set issues

### ISSUE THREAD

**Issue by HaiDaPao** [HITLDY/MSASDNet#1]
Whether the val set also needs to be processed as 256*256

**Comment by dyl96** [comment]
don't need

**Comment by HaiDaPao** [comment]
![1700556930151](https://github.com/dyl96/MSASDNet/assets/112079557/8f400bea-428b-4f3b-b89b-78be70115047)
The code seems to split the val dataset into 256*256

**Comment by dyl96** [comment]
yes, val set is 256. test set don't need

**Comment by HaiDaPao** [comment]
ok,thanks for your answer
